# Generated by Django 5.1.2 on 2024-10-24 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, null=True, verbose_name='author')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('rating', models.IntegerField(null=True, verbose_name='rated')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('appName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='feedback.feedapp')),
            ],
        ),
    ]
