# Generated by Django 5.1.2 on 2024-10-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='convo',
        ),
        migrations.AddField(
            model_name='chats',
            name='instruction',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tg_bot.chats'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
