# Generated by Django 5.1.2 on 2024-11-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_message_convo_chats_instruction_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='user_id',
            field=models.BigIntegerField(default='@@@'),
            preserve_default=False,
        ),
    ]
